### PR TITLE
[UPD] French translation

### PR DESCRIPTION
**Pull request by Gedo789**

### CODE REVIEW

**Comment by Gedo789** [comment]
Some English sentences are imprecise and will lead to improper translations/meaning in other languages.
I mean:
-"Copy DSV folder" should be "Copy DSV folder path"
-"Edit items (Luapad)" should be "Edit table content (Luapad)"

But I can't be sure since your external DB menu looks like this:
trackassemblytool_extdb_menu
By the way, is there a reason for you to remove the french accent marks? (é,è,ê,à)

**Comment by dvdvideo1234** [comment]
> Some English sentences are imprecise and will lead to improper translations/meaning in other languages.

Yes, I will adjust them right away.

> But I can't be sure since your external DB menu looks like this

The only addons that use an external database are `Plarail`, `Ron's 2ft` and `Ron's G-scale` You only need to update the tooltip strings. The ones that are labeled with `pn_ext` and marked as `New phrase PR #16`. The Context menu labels can be translated as being `pn_externdb_*`. They can be located when you hover the panel dedicated to each table or the panel tab as well as the labels in the context menu. The other for the `DSV` being `pn_ext_dsv_*` there is only the column names ( `pn_ext_dsv_1` , `pn_ext_dsv_2` ) and tooltips to be translated ;)

Thanks !

> By the way, is there a reason for you to remove the french accent marks?

No, the new phrases are entirely on English only ;).
I didn't translate them yet. I noticed that when these are missing since the
first creation of this file. Maybe it was crappy GitHub setting for the pull request
#9 that deleted them, because I only copy-pasted them as UTF8. Thank you very much
for bringing this to my attention. I will merge it right away.

**Review by dvdvideo1234 — COMMENTED** [review]
The french translation file ( `lua/trackassembly/lang/fr.lua` ) has been merged in the master branch, but the first line is detected as a diff despite containing the same amount of symbols due to having `UTF-BOM` mark. I am OK with this :dancer: This happens because both places were updated with the french accent marks. The revert of the file has been made here ;)

https://github.com/dvdvideo1234/TrackAssemblyTool/commit/f6555ccfa2134e4adcf7f09d39819b960ea9bcba

Thank you!

**Comment by dvdvideo1234** [comment]
Hello, you can now continue with phrases labeled `-- New phrase PR #16`

**Comment by dvdvideo1234** [comment]
Hello @Gedo789, you can now continue with phrases labeled `-- New phrase PR #16`. You can also take a glance at the others, and modify anything you don't think looks correct.

Thanks again ;)

**Comment by dvdvideo1234** [comment]
Thank you @Gedo789 !

**Pull request merged**
