### PR TITLE
[UPD] French translation

### PR DESCRIPTION
**Pull request by Gedo789**
Happy New Year everyone!

### CODE REVIEW

**Review by Gedo789 — COMMENTED** [review]
tSet["tool."..sTool..".workmode.1"       ] = "General spawn/snap pieces" should become tSet["tool."..sTool..".workmode.1"       ] = "(Default choice) spawn/snap pieces"
Up to you.

**Comment by dvdvideo1234** [comment]
Hello,

First of all and most important. Happy new year ;)

No. because the tool remembers the last value of the convar and updates the drop-down menu according to its value
on its first run here, because the panel modification is directly linked to it. Please leave it how it is, as it does not have such `default` value in the way it gets selected/updated:

https://github.com/dvdvideo1234/TrackAssemblyTool/blob/beb6161aa7392bdbbb07ee8f5eb4c21960bc6247/lua/weapons/gmod_tool/stools/trackassembly.lua#L2214

**Comment by dvdvideo1234** [comment]
I just saw `https://github.com/Gedo789/TrackAssemblyTool/pull/7`

So let me explain... Most of these hashes are for the tool convar tweak control menu. They update various convars with their values. Consider this `tSet["tool."..sTool..".curvefact" ] `. This is in fact the tool tip of the panel when it is hovered with the mouse. These that have `_con` are evaluated to `control` for example `tSet["tool."..sTool..".curvefact_con" ] ` just tells what the checkbox/slider/button should be labeled as. For example you have a button named `test` and when you hover on it must display `Click to test me!` ( and you click the button to test something ), so the `_con` value must be equal to `test` in this case ;) and the one without `_con` to `Click to test me!`

**Comment by Gedo789** [comment]
Done.

**Comment by dvdvideo1234** [comment]
Merci beaucoup!

**Pull request merged**
